apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak2-frontend
  namespace: boutique
spec:
  selector:
    matchLabels:
      app: ak2-frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ak2-frontend
    spec:
      serviceAccountName: default
      nodeSelector:
        node: boutique
      containers:
        - name: server
          imagePullPolicy: Always
          image: akamaslabs/frontend:0.3.6
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-liveness-probe"
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "ak-productcatalogservice:3550"
            - name: CURRENCY_SERVICE_ADDR
              value: "ak-currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "ak-cartservice:7070"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "ak-recommendationservice:8080"
            - name: SHIPPING_SERVICE_ADDR
              value: "ak-shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "ak-checkoutservice:5050"
            - name: AD_SERVICE_ADDR
              value: "ak-adservice:9555"
            - name: ENV_PLATFORM
              value: "aws"
            - name: DISABLE_TRACING
              value: "1"
            - name: DISABLE_PROFILER
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ak2-frontend
  namespace: boutique
  labels:
    app: ak2-frontend
spec:
  type: ClusterIP
  selector:
    app: ak2-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080